coverage:
  range: 60..90
  round: down
  precision: 2
  status:
    project:
      default:
        target: auto
        threshold: 05%
    patch:
      default:
        target: auto
        threshold: 05%

ignore:
  - "test"
  - "samples"
  - "perf"
