parameters:
  name: ''
  vmImage: ''
  dependsOn: ''

jobs:
  - job: ${{ parameters.name }}
    dependsOn:
      - ${{ parameters.dependsOn }}
    condition: and( succeeded(), eq( variables['Build.SourceBranch'], 'refs/heads/master' ) )
    pool:
      vmImage: ${{ parameters.vmImage }}
    timeoutInMinutes: 240
    steps:
      - task: DotNetCoreInstaller@0
        inputs:
          packageType: sdk
          version: $(SDK_VERSION)

      - bash: dotnet --list-sdks

      - task: DotNetCoreCLI@2
        inputs:
          command: run
          projects: '**/*Benchmarks/*.csproj'
          arguments: '-p perf/Benchmarks/Benchmarks.csproj -c Release -f netcoreapp3.0 -- --filter *ValidateSignedToken*'
        displayName: Run JWT validation libraries comparison benchmarks

      - task: DotNetCoreCLI@2
        inputs:
          command: run
          projects: '**/*Benchmarks/*.csproj'
          arguments: '-p perf/Benchmarks/Benchmarks.csproj -c Release -f netcoreapp3.0 -- --filter *WriteSignedToken*'
        displayName: Run JWT creation libraries comparison benchmarks

      - task: DotNetCoreCLI@2
        inputs:
          command: run
          projects: '**/*Benchmarks/*.csproj'
          arguments: '-p perf/Benchmarks/Benchmarks.csproj -c Release -f netcoreapp3.0 -- --filter *JwtBenchmark*'
        displayName: Run JWT benchmarks

      - task: DotNetCoreCLI@2
        inputs:
          command: run
          projects: '**/*Benchmarks/*.csproj'
          arguments: '-p perf/Benchmarks/Benchmarks.csproj -c Release -f netcoreapp3.0 -- --filter *JwsBenchmark*'
        displayName: Run JWS benchmarks

      - task: DotNetCoreCLI@2
        inputs:
          command: run
          projects: '**/*Benchmarks/*.csproj'
          arguments: '-p perf/Benchmarks/Benchmarks.csproj -c Release -f netcoreapp3.0 -- --filter *JweBenchmark*'
        displayName: Run JWE benchmarks

      - task: DotNetCoreCLI@2
        inputs:
          command: run
          projects: '**/*Benchmarks/*.csproj'
          arguments: '-p perf/Benchmarks/Benchmarks.csproj -c Release -f netcoreapp3.0 -- --filter *JweCompressedBenchmark*'
        displayName: Run compressed JWE benchmarks

      - bash: |
          ls -l
          ls -l perf
          ls -l perf/Benchmarks
          ls -l perf/Benchmarks/bin
          ls -l perf/Benchmarks/bin/Release
          ls -l perf/Benchmarks/bin/Release/netcoreapp3.0

      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: 'BenchmarkDotNet.Artifacts/results'
          artifactName: '${{ parameters.name }}'
