parameters:
  name: ''
  vmImage: ''
  dependsOn: ''

jobs:
  - job: ${{ parameters.name }}
    dependsOn:
      - ${{ parameters.dependsOn }}
#    condition: and( succeeded(), eq( variables['Build.SourceBranch'], 'refs/heads/master' ) )
    pool:
      vmImage: ${{ parameters.vmImage }}
    timeoutInMinutes: 90
    steps:
      - task: DotNetCoreInstaller@0
        inputs:
          packageType: sdk
          version: $(SDK_VERSION)

      - bash: ls -l

      - task: DotNetCoreCLI@2
        inputs:
          command: run
          projects: '**/*Benchmarks/*.csproj'
          arguments: '-p perf/Benchmarks/Benchmarks.csproj -c $(buildConfiguration) -f netcoreapp3.0 -- --filter *JwsBenchmark*'
        displayName: Run benchmarks
#      - bash: |
#          chmod u+x ./run-benchmarks.sh
#          ./run-benchmarks.sh

      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: 'perf/Benchmarks/bin/Release/netcoreapp3.0/BenchmarkDotNet.Artifacts/results'
          artifactName: '${{ parameters.name }}'
