parameters:
  name: ''
  vmImage: ''
  dependsOn: ''

jobs:
  - job: ${{ parameters.name }}
    dependsOn:
      - ${{ parameters.dependsOn }}
#    condition: and( succeeded(), eq( variables['Build.SourceBranch'], 'refs/heads/master' ) )
    pool:
      vmImage: ${{ parameters.vmImage }}
    timeoutInMinutes: 90
    steps:
#      - task: DotNetCoreInstaller@0
#        inputs:
#          packageType: sdk
#          version: 2.1.202
#
#      - task: DotNetCoreInstaller@0
#        inputs:
#          packageType: sdk
#          version: 2.2.100
#
#      - task: DotNetCoreInstaller@0
#        inputs:
#          packageType: sdk
#          version: 2.1.500
#
#      - task: DotNetCoreInstaller@0
#        inputs:
#          packageType: sdk
#          version: $(SDK_VERSION)
#
#      - task: DotNetCoreInstaller@0
#        inputs:
#          packageType: sdk
#          version: $(SDK_VERSION)
#
      - bash: | 
         curl -o dotnet-install.sh https://dot.net/v1/dotnet-install.sh
         mkdir dotnet
         chmod u+x ./dotnet-install.sh
         ./dotnet-install.sh --install-dir $(pwd)/dotnet -v $SDK_VERSION --Verbose
         ./dotnet-install.sh --install-dir $(pwd)/dotnet -v 2.2.100 --Verbose

      - bash: dotnet --list-sdks

      - task: DotNetCoreCLI@2
        inputs:
          command: run
          projects: '**/*Benchmarks/*.csproj'
          arguments: '-p perf/Benchmarks/Benchmarks.csproj -c Release -f netcoreapp3.0 -- --filter *JwtBenchmark*'
        displayName: Run JWT benchmarks

      - task: DotNetCoreCLI@2
        inputs:
          command: run
          projects: '**/*Benchmarks/*.csproj'
          arguments: '-p perf/Benchmarks/Benchmarks.csproj -c Release -f netcoreapp3.0 -- --filter *JwsBenchmark*'
        displayName: Run JWS benchmarks

      - task: DotNetCoreCLI@2
        inputs:
          command: run
          projects: '**/*Benchmarks/*.csproj'
          arguments: '-p perf/Benchmarks/Benchmarks.csproj -c Release -f netcoreapp3.0 -- --filter *JweBenchmark*'
        displayName: Run JWE benchmarks

      - task: DotNetCoreCLI@2
        inputs:
          command: run
          projects: '**/*Benchmarks/*.csproj'
          arguments: '-p perf/Benchmarks/Benchmarks.csproj -c Release -f netcoreapp3.0 -- --filter *JweCompressedBenchmark*'
        displayName: Run compressed JWE benchmarks

      - bash: |
          ls -l
          ls -l perf
          ls -l perf/Benchmarks
          ls -l perf/Benchmarks/bin
          ls -l perf/Benchmarks/bin/Release
          ls -l perf/Benchmarks/bin/Release/netcoreapp3.0

      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: 'BenchmarkDotNet.Artifacts/results'
          artifactName: '${{ parameters.name }}'